# Generated by Django 3.2.18 on 2023-10-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
